version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: user_service
    ports:
      - "${POSTGRES_PORT}:5432" # Mapowanie portu na hoście
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - user_data:/var/lib/postgresql/data # Trwałe przechowywanie danych

volumes:
  user_data:
